### ISSUE TITLE
Dropdown `I am a...`

### ISSUE THREAD

**Issue by ijpatricio** [protect-earth/protect.earth#36] opened 2020-04-05 23:03 UTC
Complete the links to tags for the various target audiences.

**Comment by philsturgeon** [comment] 2020-04-06 12:36
Also, noticed a funny issue loading with a slow connection.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67381/78557446-b8940000-7808-11ea-8a0f-cb08d7256e0a.png">

**Comment by Squallac** [comment] 2020-04-08 14:03
I can work on this

**Comment by Squallac** [comment] 2020-04-08 14:17
Oh sorry I didn't noticed you were assigned to this, I'll look for something else haha

**Comment by ijpatricio** [comment] 2020-04-08 14:56
Hello @Squallac , that's not a problem, you're assigned now. I'll review it.

Keep it like your previous work, small and concise. Better to have smaller and quick iterations ;)

Let me know if you need any hands on deck!

**Comment by Squallac** [comment] 2020-04-08 16:15
> Also, noticed a funny issue loading with ~a slow connection~ it stays there actually, in Firefox but not Safari..
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/67381/78557446-b8940000-7808-11ea-8a0f-cb08d7256e0a.png">

I wasn't able to reproduce this issue, I tested with firefox and Chrome in Ubuntu using slow connection throttle. This might be an issue with the bundle size?

**Comment by Squallac** [comment] 2020-04-08 16:18
PR Open https://github.com/protect-earth/protect.earth/pull/42

**Comment by philsturgeon** [comment] 2020-04-08 16:20
@Squallac can you see the issue on https://new.protect.earth/ in FF?

**Comment by Squallac** [comment] 2020-04-08 16:27
> @Squallac can you see the issue on https://new.protect.earth/ in FF?

Oh yeah I can see it! Let me take a look

**Comment by philsturgeon** [comment] 2020-04-13 14:00
I'd love to get this killed off. I keep bumping into it every time I preview the site. 😆

**Comment by Squallac** [comment] 2020-04-15 15:09
I was taking a look to the 

> Also, noticed a funny issue loading with ~a slow connection~ it stays there actually, in Firefox but not Safari..
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/67381/78557446-b8940000-7808-11ea-8a0f-cb08d7256e0a.png">

I was taking a look to this issue, it looks like its not loading the css classes "ml-1 h-5 w-5" on the svg file.

Do you think this could be an issue with the tailwindCSS config @ijpatricio ? I'm not familiar with the config of tailwind

**Comment by ijpatricio** [comment] 2020-04-15 17:19
With your findings, I set the prop to not display the inner svg, and put it our own (the same) on the content slot, so that I could override the styles directly on the element.

Better done than perfect, when and if it will be a problem, we'll take care of that. For now it's done, I've made a quick PR.

Thank you @Squallac

**Comment by philsturgeon** [comment] 2020-04-15 17:33
Thank you @ijpatricio!

**Comment by philsturgeon** [comment] 2020-04-15 17:34
Also thank you @Squallac great teamwork.

**Closed by philsturgeon** 2020-04-15 17:33 UTC
